### ISSUE TITLE
redirect throw error [Cannot modify header information - headers already sent]

### ISSUE THREAD

**Issue by zahidmuhammadzaki** [luka-zitnik/CodeIgniterModule#4]
Functional test

```
public function register_with_email_already_registered_show_alert_error(FunctionalTester $I)
    {
      $I->wantTo('Register with email that is aleaready registered.');
      $I->haveInDatabase(Tables::$tableUser, [Tables::$tableUserFieldEmail => RegisterPage::$valueEmailExists]);
      $I->amOnPage(RegisterPage::$URL);
      $I->see(RegisterPage::$textRegisterFormHeader);
      $I->fillField(RegisterPage::$fieldName, RegisterPage::$valueName);
      $I->fillField(RegisterPage::$fieldEmail, RegisterPage::$valueEmailExists);
      $I->fillField(RegisterPage::$fieldPassword, RegisterPage::$valuePassword);
      $I->fillField(RegisterPage::$fieldPasswordConfirmation, RegisterPage::$valuePassword);
      $I->click(RegisterPage::$btnRegister);
      $I->see(RegisterPage::$textRegisterFormHeader);
      $I->see(RegisterPage::$alertEmailExists);
    }
```

It should redirect to `auth/register`.

Here is the error

![capture](https://cloud.githubusercontent.com/assets/8657754/19477154/f74a54bc-9566-11e6-8e4e-30b4bd30689e.JPG)

**Comment by luka-zitnik** [comment]
I can only guess the first line of `application/modules/auth/models/repo/Auth_repo.php` echoes new line character before header is made by a call to `redirect()` in `application/modules/auth/controllers/Auth.php`. You may want to try clearing it.

Otherwise you may want to push the changes to the repository you've made, so I can see exactly how your code interacts with the CodeIgniterModule and possibly remove the cause that makes your application run differently in a functional test, if so.

**Comment by zahidmuhammadzaki** [comment]
Rigth. There empty line there.

Sorry if the response quite long.

But the test is still not working because of other reasons.

I already commit to the repository. In the branch with prefix "issue/*".

**Comment by luka-zitnik** [comment]
This was quite unexpected to me, multiple cookies were not supported. I based the module on the Universal Connector from the Codeception project and brought in an error along.

Anyways, there's a new patch on the master branch. It should fix the issue.

But there's another problem. Wherever there's an `exit` statement in the execution path of a use case, that use case cannot be made into a test with this module. At least so far as I can see now. If you are willing to abandon `exit` statement for those use cases in order to cover them with functional tests using this module, you can do it e.g. by replacing

``` php
redirect(uri_string());
```

with

``` php
header('Location: ' . uri_string(), TRUE, 302);
return;
```

**Comment by zahidmuhammadzaki** [comment]
Nice. It works.

I try to fix this. You can see my pull request. 

This is my first contribution on open source project. So, do not hesitate to criticize it.

**Comment by luka-zitnik** [comment]
OK. I will leave this thread until I add a test and turn the change into a new release.

**Comment by luka-zitnik** [comment]
v1.0.3 is out
